// levels.js — Level definitions
const LEVELS = [
  {
    id: 1,
    name: 'Fortryllet Skov',
    snakeName: 'Lille grøn skovslange',
    snakeColor: { h: 120, s: 70, l: 45 }, // green
    snakeAccent: '#90ee90',
    bgColor: '#1a3a1a',
    itemEmoji: '🍄',
    itemName: 'magiske svampe',
    itemsNeeded: 5,
    speed: 180, // ms per tick (higher = slower)
    obstacles: 0,
    obstacleColor: '#555'
  },
  {
    id: 2,
    name: 'Magisk Sø',
    snakeName: 'Vandslange',
    snakeColor: { h: 200, s: 80, l: 50 },
    snakeAccent: '#88ddff',
    bgColor: '#0a2a3a',
    itemEmoji: '🫧',
    itemName: 'perler',
    itemsNeeded: 7,
    speed: 170,
    obstacles: 0,
    obstacleColor: '#555'
  },
  {
    id: 3,
    name: 'Feernes Have',
    snakeName: 'Blomsterslange',
    snakeColor: { h: 330, s: 75, l: 60 },
    snakeAccent: '#ffaacc',
    bgColor: '#2a1a2a',
    itemEmoji: '🌸',
    itemName: 'magiske blomster',
    itemsNeeded: 8,
    speed: 165,
    obstacles: 0,
    obstacleColor: '#555'
  },
  {
    id: 4,
    name: 'Vulkanhule',
    snakeName: 'Ildslange',
    snakeColor: { h: 15, s: 85, l: 50 },
    snakeAccent: '#ff8844',
    bgColor: '#2a0a0a',
    itemEmoji: '💎',
    itemName: 'flamme-krystaller',
    itemsNeeded: 9,
    speed: 160,
    obstacles: 3,
    obstacleColor: '#666'
  },
  {
    id: 5,
    name: 'Nattehimmel',
    snakeName: 'Stjerneslange',
    snakeColor: { h: 50, s: 90, l: 55 },
    snakeAccent: '#ffee77',
    bgColor: '#0a0a2a',
    itemEmoji: '⭐',
    itemName: 'faldende stjerner',
    itemsNeeded: 10,
    speed: 155,
    obstacles: 4,
    obstacleColor: '#334'
  },
  {
    id: 6,
    name: 'Krystalgrotte',
    snakeName: 'Krystalslange',
    snakeColor: { h: 280, s: 70, l: 55 },
    snakeAccent: '#cc88ff',
    bgColor: '#1a0a3a',
    itemEmoji: '💠',
    itemName: 'ædelstene',
    itemsNeeded: 10,
    speed: 150,
    obstacles: 5,
    obstacleColor: '#446'
  },
  {
    id: 7,
    name: 'Skyrige',
    snakeName: 'Regnbueslange',
    snakeColor: { h: 0, s: 80, l: 60 }, // will be rainbow-rendered
    snakeAccent: '#ffffff',
    isRainbow: true,
    bgColor: '#1a2a3a',
    itemEmoji: '🌈',
    itemName: 'regnbue-dråber',
    itemsNeeded: 10,
    speed: 145,
    obstacles: 5,
    obstacleColor: '#889'
  },
  {
    id: 8,
    name: 'Dragefjeld',
    snakeName: 'Lille drage',
    snakeColor: { h: 0, s: 75, l: 45 },
    snakeAccent: '#ff6644',
    bgColor: '#2a1a0a',
    itemEmoji: '🥚',
    itemName: 'drageæg',
    itemsNeeded: 10,
    speed: 140,
    obstacles: 6,
    obstacleColor: '#665'
  },
  {
    id: 9,
    name: 'Frosset Slot',
    snakeName: 'Isslange',
    snakeColor: { h: 195, s: 60, l: 75 },
    snakeAccent: '#cceeff',
    bgColor: '#0a1a2a',
    itemEmoji: '❄️',
    itemName: 'snefnug',
    itemsNeeded: 10,
    speed: 135,
    obstacles: 6,
    obstacleColor: '#99b'
  },
  {
    id: 10,
    name: 'Tronesal',
    snakeName: 'Gylden Dronningeslange',
    snakeColor: { h: 45, s: 90, l: 55 },
    snakeAccent: '#ffd700',
    bgColor: '#2a1a0a',
    itemEmoji: '👑',
    itemName: 'kroner & juveler',
    itemsNeeded: 10,
    speed: 130,
    obstacles: 7,
    obstacleColor: '#886'
  }
];
